### ISSUE TITLE
Fatal Error for device lookup 

### ISSUE THREAD

**Issue by rolinger** [EdwinHoksberg/php-fcm#14]
It works fine if there is a valid ID to return info on.  But causes a fatal error if the ID can't be found.

```
  $deviceID = "eNoPRU6hj00:APA91bHt5BGE9TqIyMnFkOQd899gSoUUoNQNc8sdHyo0hV10Q63E-zgq4BEc4GI-3sFqQv0YQ6tbOhFGTRKO5kZ7DmJhSmnoThP6rOWv0Ac8Y9A6PkH6Sr9UUFOiKIUsndLSJX8JpO7t" ;
  $info = new \Fcm\Device\Info($deviceID, true);
  $response =  $client->send($info);
  foreach ($response['rel']['topics'] as $key => $value) {
    echo "\n\tTopic: $key" ;
  }
  print_r($response) ;
```

It looks like the response is being generated from google, but not being processed in the return handler.

```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://iid.googleapis.com/iid/info/eNoPRU6hj00:APA91bHt5BGE9TqIyMnFkOQd899gSoUUoNQNc8sdHyo0hV10Q63E-zgq4BEc4GI-3sFqQv0YQ6tbOhFGTRKO5kZ7DmJhSmnoThP6rOWv0Ac8Y9A6PkH6Sr9UUFOiKIUsndLSJX8JpO7t?details=true` resulted in a `404 Not Found` response:
{"error":"No information found about this instance id."}
 in /home/myServer/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/myServer/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/myServer/public_html/api/assets/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/myServer/public_html/api/assets/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleH in /home/whipsteradmin/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

```

**Comment by rolinger** [comment]
Resolved with https://github.com/EdwinHoksberg/php-fcm/issues/17
